import type { MapNode } from "./types"

export const mapNodes: MapNode[] = [
  // Beginner - Foundations Phase
  {
    id: "futures-basics",
    title: "Futures Basics",
    slug: "futures-basics",
    level: "Beginner",
    tags: ["Structure"],
    summary: "Understand what futures contracts are and how they work.",
    prereqs: [],
    timeMinutes: 10,
    pathIds: ["foundations"],
    position: { x: 150, y: 100 },
    phase: "foundations", // Added phase
  },
  {
    id: "tick-values",
    title: "Tick Values & Contract Specs",
    slug: "tick-values",
    level: "Beginner",
    tags: ["Structure"],
    summary: "Learn about tick sizes, point values, and how to calculate P&L.",
    prereqs: ["futures-basics"],
    timeMinutes: 8,
    pathIds: ["foundations"],
    position: { x: 400, y: 100 },
    phase: "foundations",
  },
  {
    id: "margin-leverage",
    title: "Margin & Leverage",
    slug: "margin-leverage",
    level: "Beginner",
    tags: ["Risk", "Structure"],
    summary: "Understand margin requirements and the double-edged sword of leverage.",
    prereqs: ["tick-values"],
    timeMinutes: 12,
    pathIds: ["foundations"],
    position: { x: 650, y: 100 },
    phase: "foundations",
  },
  {
    id: "market-structure",
    title: "Market Structure",
    slug: "market-structure",
    level: "Beginner",
    tags: ["Structure"],
    summary: "Identify trends, ranges, and key structural levels.",
    prereqs: ["futures-basics"],
    timeMinutes: 15,
    pathIds: ["foundations"],
    position: { x: 150, y: 200 },
    phase: "foundations",
  },
  {
    id: "session-timing",
    title: "Session Timing",
    slug: "session-timing",
    level: "Beginner",
    tags: ["Structure", "Execution"],
    summary: "Learn about market sessions and when volatility typically occurs.",
    prereqs: ["market-structure"],
    timeMinutes: 8,
    pathIds: ["foundations"],
    position: { x: 400, y: 200 },
    phase: "foundations",
  },
  {
    id: "risk-fundamentals",
    title: "Risk Fundamentals",
    slug: "risk-fundamentals",
    level: "Beginner",
    tags: ["Risk"],
    summary: "Core principles of risk management every trader must know.",
    prereqs: ["margin-leverage"],
    timeMinutes: 12,
    pathIds: ["foundations"],
    position: { x: 900, y: 100 },
    phase: "foundations",
  },
  {
    id: "trading-psychology-intro",
    title: "Trading Psychology Intro",
    slug: "trading-psychology-intro",
    level: "Beginner",
    tags: ["Psychology"],
    summary: "Why mindset matters more than strategy in trading.",
    prereqs: ["risk-fundamentals"],
    timeMinutes: 10,
    pathIds: ["foundations"],
    position: { x: 900, y: 200 },
    phase: "foundations",
  },

  // Intermediate - Split between Foundations and Execution
  {
    id: "position-sizing",
    title: "Position Sizing",
    slug: "position-sizing",
    level: "Intermediate",
    tags: ["Risk", "Execution"],
    summary: "Calculate proper position sizes based on account risk.",
    prereqs: ["risk-fundamentals", "tick-values"],
    timeMinutes: 15,
    pathIds: ["foundations", "execution", "risk-management"],
    position: { x: 150, y: 350 },
    phase: "foundations", // Risk-related, part of foundations
  },
  {
    id: "stop-placement",
    title: "Stop Placement",
    slug: "stop-placement",
    level: "Intermediate",
    tags: ["Risk", "Execution"],
    summary: "Learn where to place stops based on structure, not arbitrary amounts.",
    prereqs: ["position-sizing", "market-structure"],
    timeMinutes: 12,
    pathIds: ["execution"],
    position: { x: 400, y: 350 },
    phase: "foundations", // Risk-related, part of foundations
  },
  {
    id: "breakout-entries",
    title: "Breakout Entries",
    slug: "breakout-entries",
    level: "Intermediate",
    tags: ["Execution", "Structure"],
    summary: "Identify and execute breakout trades with proper confirmation.",
    prereqs: ["market-structure", "session-timing"],
    timeMinutes: 18,
    pathIds: ["execution"],
    position: { x: 650, y: 350 },
    phase: "execution", // Execution phase
  },
  {
    id: "pullback-entries",
    title: "Pullback Entries",
    slug: "pullback-entries",
    level: "Intermediate",
    tags: ["Execution", "Structure"],
    summary: "Enter trends on pullbacks for better risk-reward.",
    prereqs: ["breakout-entries"],
    timeMinutes: 15,
    pathIds: ["execution"],
    position: { x: 900, y: 350 },
    phase: "execution",
  },
  {
    id: "trade-management",
    title: "Trade Management",
    slug: "trade-management",
    level: "Intermediate",
    tags: ["Execution", "Risk"],
    summary: "Manage open positions with partials, trailing stops, and targets.",
    prereqs: ["stop-placement", "breakout-entries"],
    timeMinutes: 20,
    pathIds: ["execution"],
    position: { x: 650, y: 450 },
    phase: "execution",
  },
  {
    id: "journaling-basics",
    title: "Journaling Basics",
    slug: "journaling-basics",
    level: "Intermediate",
    tags: ["Journaling", "Psychology"],
    summary: "What to track in your trading journal and why it matters.",
    prereqs: ["trading-psychology-intro"],
    timeMinutes: 12,
    pathIds: ["foundations", "trading-psychology"],
    position: { x: 1150, y: 350 },
    phase: "mastery", // Psychology/journaling is mastery
  },
  {
    id: "diversification-position-sizing",
    title: "Diversification & Position Sizing",
    slug: "diversification-position-sizing",
    level: "Intermediate",
    tags: ["Risk"],
    summary: "Spread risk across contracts and calculate sizes based on equity and tolerance.",
    prereqs: ["position-sizing"],
    timeMinutes: 18,
    pathIds: ["risk-management"],
    position: { x: 150, y: 450 },
    phase: "foundations",
  },
  {
    id: "stop-loss-risk-reward",
    title: "Stop-Loss Orders & Risk/Reward",
    slug: "stop-loss-risk-reward",
    level: "Intermediate",
    tags: ["Risk", "Execution"],
    summary: "Define stops with ATR and understand risk-to-reward ratios.",
    prereqs: ["diversification-position-sizing", "stop-placement"],
    timeMinutes: 15,
    pathIds: ["risk-management"],
    position: { x: 400, y: 450 },
    phase: "foundations",
  },
  {
    id: "risk-management-tools",
    title: "Risk Management Tools",
    slug: "risk-management-tools",
    level: "Intermediate",
    tags: ["Risk"],
    summary: "ATR-based stops, position calculators, and daily loss limits.",
    prereqs: ["stop-loss-risk-reward"],
    timeMinutes: 20,
    pathIds: ["risk-management"],
    position: { x: 150, y: 550 },
    phase: "foundations",
  },
  {
    id: "mindset-discipline",
    title: "Mindset & Discipline",
    slug: "mindset-discipline",
    level: "Intermediate",
    tags: ["Psychology"],
    summary: "Emotional decisions cause losses—discipline and a plan fix it.",
    prereqs: ["trading-psychology-intro"],
    timeMinutes: 18,
    pathIds: ["trading-psychology"],
    position: { x: 1150, y: 450 },
    phase: "mastery",
  },
  {
    id: "journaling-accountability",
    title: "Journaling & Accountability",
    slug: "journaling-accountability",
    level: "Intermediate",
    tags: ["Journaling", "Psychology"],
    summary: "Record trades, emotions, and rationale to improve decisions.",
    prereqs: ["journaling-basics", "mindset-discipline"],
    timeMinutes: 15,
    pathIds: ["trading-psychology"],
    position: { x: 1150, y: 550 },
    phase: "mastery",
  },
  {
    id: "overtrading-revenge",
    title: "Overtrading & Revenge Trading",
    slug: "overtrading-revenge",
    level: "Intermediate",
    tags: ["Psychology", "Risk"],
    summary: "Recognize and stop destructive trading patterns before they start.",
    prereqs: ["journaling-accountability"],
    timeMinutes: 15,
    pathIds: ["trading-psychology"],
    position: { x: 900, y: 550 },
    phase: "mastery",
  },

  // Advanced - Split between Execution and Mastery
  {
    id: "order-flow-basics",
    title: "Order Flow Basics",
    slug: "order-flow-basics",
    level: "Advanced",
    tags: ["Order Flow", "Execution"],
    summary: "Understand WHY price moves through aggressive vs passive order analysis.",
    prereqs: ["market-structure"],
    timeMinutes: 25,
    pathIds: ["order-flow", "execution"],
    position: { x: 150, y: 700 },
    phase: "execution",
  },
  {
    id: "absorption-rejection",
    title: "Absorption and Rejection",
    slug: "absorption-rejection",
    level: "Advanced",
    tags: ["Order Flow", "Execution"],
    summary: "Recognize when large players defend levels and when reversals are likely.",
    prereqs: ["order-flow-basics"],
    timeMinutes: 22,
    pathIds: ["order-flow"],
    position: { x: 400, y: 700 },
    phase: "execution",
  },
  {
    id: "delta-imbalance",
    title: "Delta and Imbalance",
    slug: "delta-imbalance",
    level: "Advanced",
    tags: ["Order Flow", "Execution"],
    summary: "Use delta divergence and imbalances to spot exhaustion before reversals.",
    prereqs: ["order-flow-basics"],
    timeMinutes: 22,
    pathIds: ["order-flow"],
    position: { x: 400, y: 800 },
    phase: "execution",
  },
  {
    id: "when-not-order-flow",
    title: "When Not to Trade Order Flow",
    slug: "when-not-order-flow",
    level: "Advanced",
    tags: ["Order Flow", "Execution"],
    summary: "Know when order flow analysis fails and when to step aside.",
    prereqs: ["order-flow-basics"],
    timeMinutes: 18,
    pathIds: ["order-flow"],
    position: { x: 650, y: 750 },
    phase: "execution",
  },
  {
    id: "playbook-building",
    title: "Playbook Building",
    slug: "playbook-building",
    level: "Advanced",
    tags: ["Execution", "Journaling"],
    summary: "Create a personal playbook of high-probability setups.",
    prereqs: ["journaling-basics", "trade-management"],
    timeMinutes: 20,
    pathIds: ["execution"],
    position: { x: 900, y: 700 },
    phase: "execution",
  },
  {
    id: "revenge-trading",
    title: "Revenge Trading",
    slug: "revenge-trading",
    level: "Advanced",
    tags: ["Psychology", "Risk"],
    summary: "Recognize and prevent the destructive pattern of revenge trading.",
    prereqs: ["trading-psychology-intro", "journaling-basics"],
    timeMinutes: 15,
    pathIds: ["foundations", "trading-psychology"],
    position: { x: 1150, y: 700 },
    phase: "mastery",
  },
  {
    id: "drawdown-recovery",
    title: "Drawdown Recovery Plan",
    slug: "drawdown-recovery",
    level: "Advanced",
    tags: ["Psychology", "Risk"],
    summary: "Systematic approach to recovering from drawdowns without blowing up.",
    prereqs: ["revenge-trading", "position-sizing"],
    timeMinutes: 18,
    pathIds: ["foundations", "risk-management"],
    position: { x: 900, y: 800 },
    phase: "mastery",
  },
  {
    id: "advanced-review",
    title: "Advanced Trade Review",
    slug: "advanced-review",
    level: "Advanced",
    tags: ["Journaling", "Psychology"],
    summary: "Deep dive into analyzing your trades for continuous improvement.",
    prereqs: ["playbook-building", "journaling-basics"],
    timeMinutes: 22,
    pathIds: ["execution", "trading-psychology"],
    position: { x: 1150, y: 800 },
    phase: "mastery",
  },
]

export function getNodeById(id: string): MapNode | undefined {
  return mapNodes.find((n) => n.id === id)
}

export function getNodeBySlug(slug: string): MapNode | undefined {
  return mapNodes.find((n) => n.slug === slug)
}

export function getNodesByPhase(phase: string): MapNode[] {
  return mapNodes.filter((n) => n.phase === phase)
}
